### PR TITLE
declare dependencies

### PR DESCRIPTION
**Pull request by elharo**
@dennisl

### CODE REVIEW

**Comment by slachiewicz** [comment]
Any reason why we need to declare these dependencies? org.eclipse.sisu.plexus is a transitive dependency from maven plugin API
and with each update to minimum maven.version property someone needs to adjust also this one instead of giving Maven chance to do its job.

**Comment by elharo** [comment]
If one specifically imports classes from these dependencies, then they should be declared. Relaying on transitive dependencies is brittle. 5 months later I don't recall exactly which classes are imported from where but mvn dependency:analyze will find anything that's not needed.

**Comment by dennisl** [comment]
I agree with @elharo

**Comment by slachiewicz** [comment]
thx @dennisl  - would you be able to sync the maven version to 3.1.1 as try to confirm that this proposed approach works?

**Comment by slachiewicz** [comment]
```
[INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ maven-filtering ---
[WARNING] Used undeclared dependencies found:
[WARNING]    org.hamcrest:hamcrest:jar:2.2:test
[WARNING]    org.eclipse.aether:aether-api:jar:0.9.0.M2:compile
[WARNING] Unused declared dependencies found:
[WARNING]    org.hamcrest:hamcrest-core:jar:2.2:test



```

**Comment by slachiewicz** [comment]
With each minimum Maven upgrade, someone needs to review all deps and update the version of aether to match with that will be delivered by Maven installation. No older, no newer.

**Comment by slachiewicz** [comment]
real case: https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1091

**Pull request merged**
