### PR TITLE
[MSHARED-1412] Allow to customize Interpolator used by filter

### PR DESCRIPTION
**Pull request by kwin**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MSHARED) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MSHARED-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MSHARED-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify -Prun-its` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by gnodet** [comment]
@kwin is there an immediate use case for this ? which maven plugin will use it ? just curious...

**Comment by kwin** [comment]
The use case for me is https://issues.apache.org/jira/browse/JCRVLT-757 (outside the Maven project). But I can imagine that for some advanced use cases also the `maven-resources-plugin` could leverage that (with automatically registered Sisu components)...

**Comment by olamy** [comment]
is there anything you could do with this https://maven.apache.org/plugins/maven-resources-plugin/examples/custom-resource-filters.html ?

**Comment by kwin** [comment]
The problem is I want the default filter behaviour, which is currently not reusable in custom filter (i.e. all the code from https://github.com/apache/maven-filtering/blob/9d528d0871d93e317ae21a4b6922cd795502364c/src/main/java/org/apache/maven/shared/filtering/BaseFilter.java#L74-L181 and https://github.com/apache/maven-filtering/blob/9d528d0871d93e317ae21a4b6922cd795502364c/src/main/java/org/apache/maven/shared/filtering/BaseFilter.java#L217-L323 would need to be duplicated for a custom filter). The interpolator customizer allows to leverage the default filterwhile still extending interpolation features of it.

**Comment by kwin** [comment]
If there is no further input I will merge at the end of the week.

**Review by slachiewicz — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #263

**Pull request merged**
